-- 1. Create documents table (Generated content storage)
create table if not exists public.documents (
  id uuid default uuid_generate_v4() primary key,
  user_id uuid references auth.users, -- FK, but nullable for anonymous users
  diagnostic_id uuid references public.diagnostic_results(id), -- Link to source diagnostic if available (optional)
  title text not null, -- e.g. "Safety Certification Application"
  doc_type text not null, -- e.g. "application_form", "manual"
  content text not null, -- Markdown content generated by AI
  status text default 'draft', -- 'draft', 'final'
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. Enable RLS
alter table public.documents enable row level security;

-- 3. Create policies for public access (Demo mode)
create policy "Anyone can insert documents" on public.documents for insert with check (true);
create policy "Anyone can view documents" on public.documents for select using (true);
