name = "compliance-saas"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[[d1_databases]]
binding = "DB"
database_name = "compliance-saas-db"
database_id = "14e04fa6-3afe-40a5-b1b6-592102dbbc76"

[[r2_buckets]]
binding = "STORAGE"
bucket_name = "compliance-saas-documents"

[vars]
APP_URL = "https://compliance-saas-5jq.pages.dev"
CLOUDFLARE_ACCOUNT_ID = "85c8e953bdefb825af5374f0d66ca5dc"
EMAIL_FROM = "noreply@example.com"
EMAIL_FROM_NAME = "Certi-Mate"
